'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ApiClient

    '''<summary>
    '''loginDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPassword As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''btnApiLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApiLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblLoginResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnApiLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApiLogout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAllProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllProducts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvAllProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllProducts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnAllReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllReviews As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvAllReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllReviews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProductID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProductID As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReviewID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReviewID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReviewID As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbProductNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductDescription As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbSubCategoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubCategoryID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbFeatured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFeatured As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbMainCategoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMainCategoryID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCreateProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbUpdateProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnUpdateProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbRProductId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRProductId As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUserName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRating As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbUserReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUserReview As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCreateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbUpdateReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateReviewID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnUpdateReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbDeleteProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeleteProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnDeleteProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteProductID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbDeleteReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeleteReviewID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnDeleteReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteReviewID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAllCarts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllCarts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvAllCarts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllCarts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbDeleteCartLineID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeleteCartLineID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnDeleteCartLineID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCartLineID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbGetCartID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGetCartID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCartByID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCartByID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvCartByID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCartByID As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnCurrentCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCurrentCart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvCurrentCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCurrentCart As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbUpdateQtyCartLineID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateQtyCartLineID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbUpdateQtyAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateQtyAmt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnUpdateCartQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateCartQty As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnImportAllProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportAllProducts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnImportAllReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportAllReviews As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbImportProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbImportProductID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnImportProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportProductID As Global.System.Web.UI.WebControls.Button
End Class
